name: Pull Request Workflow
on: [pull_request]
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: main
          pr_title: 'Pull Request from ${{ github.head_ref }} to ${{ github.base_ref }}'
          pr_body: |
            :robot: This pull request was automatically

            _Created by [repo-sync/pull-request](https://github.com/repo-sync/pull-request)_
          pr_template: '.github/PULL_REQUEST_TEMPLATE.md'
          pr_reviewers: 'github-actions[bot]'
          pr_assignees: 'github-actions[bot]'
          pr_labels: 'auto-pr'
          pr_milestone: 'Milestone 1'
          pr_draft: true
          pr_allow_empty: true
      - name: output
        run: |
          echo "Pull Request Number - ${{ steps.open-pr.outputs.pr_number }}"
          echo "Pull Request URL - ${{ steps.open-pr.outputs.pr_url }}"
          echo "Pull Request Created - ${{ steps.open-pr.outputs.pr_created }}"
